# Generated by Django 5.0.2 on 2024-02-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kanji',
            old_name='jlpt_level',
            new_name='frequency',
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='meaning',
        ),
        migrations.AddField(
            model_name='kanji',
            name='jlpt_new',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kanji',
            name='jlpt_old',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kanji',
            name='meanings',
            field=models.JSONField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kanji',
            name='readings_kun',
            field=models.JSONField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kanji',
            name='readings_on',
            field=models.JSONField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kanji',
            name='strokes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kanji',
            name='wk_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kanji',
            name='character',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
