# Generated by Django 5.0.2 on 2024-02-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji_app', '0002_rename_jlpt_level_kanji_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kanji',
            name='kanken_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
